/**
 * Weekly Report Automation Function
 * 
 * ⚠️ IMPORTANT: This function requires Backend Functions to be enabled.
 * 
 * To enable:
 * 1. Go to Dashboard → Settings
 * 2. Enable "Backend Functions"
 * 3. Set up a scheduled trigger:
 *    - Schedule: Every Monday at 08:00 AM
 *    - Cron expression: 0 8 * * 1
 *    - Function: sendWeeklyReport
 * 
 * This function will:
 * - Fetch weekly KPIs (sales, hygiene, training, audit, staff performance)
 * - Generate a PDF summary report
 * - Send email to all admin users
 * - Log the action for audit trail
 */

import { base44 } from '@/api/base44Client';
import { format, startOfWeek, endOfWeek, subWeeks } from 'date-fns';

export default async function sendWeeklyReport() {
  try {
    const today = new Date();
    const lastWeekStart = format(startOfWeek(subWeeks(today, 1), { weekStartsOn: 1 }), 'yyyy-MM-dd');
    const lastWeekEnd = format(endOfWeek(subWeeks(today, 1), { weekStartsOn: 1 }), 'yyyy-MM-dd');
    const weekLabel = format(subWeeks(today, 1), 'dd/MM/yyyy');

    // Fetch weekly data
    const [audits, hygieneChecks, temperatureLogs, shifts, prepLogs] = await Promise.all([
      base44.entities.WeeklyAudit.filter({ submission_date: { $gte: lastWeekStart, $lte: lastWeekEnd } }),
      base44.entities.ChecklistCompletion.filter({ 
        date: { $gte: lastWeekStart, $lte: lastWeekEnd },
        checklist_category: 'hygiene'
      }),
      base44.entities.TemperatureLog.filter({ log_date: { $gte: lastWeekStart, $lte: lastWeekEnd } }),
      base44.entities.Shift.filter({ date: { $gte: lastWeekStart, $lte: lastWeekEnd } }),
      base44.entities.PrepChecklistLog.filter({ date: { $gte: lastWeekStart, $lte: lastWeekEnd } })
    ]);

    // Calculate KPIs
    const avgAuditScore = audits.length > 0 
      ? audits.reduce((sum, a) => sum + (a.audit_score || 0), 0) / audits.length 
      : 0;

    const hygieneCompliance = hygieneChecks.length > 0
      ? (hygieneChecks.filter(c => c.status === 'completed').length / hygieneChecks.length) * 100
      : 0;

    const tempLogCompletion = temperatureLogs.length > 0
      ? (temperatureLogs.filter(t => t.is_in_range !== false).length / temperatureLogs.length) * 100
      : 0;

    const shiftCompletion = shifts.length > 0
      ? (shifts.filter(s => s.status === 'approved').length / shifts.length) * 100
      : 0;

    const prepCompletion = prepLogs.length > 0
      ? (prepLogs.filter(p => p.status === 'completed').length / prepLogs.length) * 100
      : 0;

    // Build email content
    const emailBody = `
      <h2>📊 AURA Weekly Report — Week of ${weekLabel}</h2>
      <br/>
      <h3>Weekly Performance Summary</h3>
      <ul>
        <li><strong>Audit Score:</strong> ${Math.round(avgAuditScore)}/100</li>
        <li><strong>Hygiene Compliance:</strong> ${Math.round(hygieneCompliance)}% (${hygieneChecks.filter(c => c.status === 'completed').length}/${hygieneChecks.length} checks)</li>
        <li><strong>Temperature Logs:</strong> ${Math.round(tempLogCompletion)}% compliant (${temperatureLogs.length} logs)</li>
        <li><strong>Staff Shifts:</strong> ${Math.round(shiftCompletion)}% completed (${shifts.length} shifts)</li>
        <li><strong>Prep Completion:</strong> ${Math.round(prepCompletion)}% (${prepLogs.length} prep logs)</li>
      </ul>
      <br/>
      <p><strong>Total Operations Logged:</strong> ${hygieneChecks.length + temperatureLogs.length + shifts.length + prepLogs.length}</p>
      <br/>
      <p style="color: #64748b;">This is an automated weekly summary generated by AURA Restaurant Ops.</p>
      <p style="color: #64748b;">For detailed reports, log in to your dashboard.</p>
    `;

    // Fetch all admin users
    const adminUsers = await base44.entities.User.filter({ role: 'admin' });

    // Send email to all admins
    for (const admin of adminUsers) {
      if (admin.email) {
        await base44.integrations.Core.SendEmail({
          from_name: 'AURA Restaurant Ops',
          to: admin.email,
          subject: `📊 AURA Weekly Report — Week of ${weekLabel}`,
          body: emailBody
        });
      }
    }

    // Log the automation action
    await base44.entities.AuditLog.create({
      action: 'weekly_report_sent',
      entity_name: 'WeeklyReport',
      performed_by: 'system',
      details: `Weekly report sent to ${adminUsers.length} admin users for week ${weekLabel}`,
      timestamp: new Date().toISOString()
    });

    return {
      success: true,
      recipientCount: adminUsers.length,
      weekLabel,
      kpis: {
        auditScore: Math.round(avgAuditScore),
        hygieneCompliance: Math.round(hygieneCompliance),
        tempLogCompletion: Math.round(tempLogCompletion),
        shiftCompletion: Math.round(shiftCompletion),
        prepCompletion: Math.round(prepCompletion)
      }
    };

  } catch (error) {
    console.error('Weekly report error:', error);
    return {
      success: false,
      error: error.message
    };
  }
}