import React, { useState, useEffect } from 'react';
import { base44 } from '@/api/base44Client';
import { useQuery } from '@tanstack/react-query';
import { motion } from 'framer-motion';
import { format, subDays, startOfMonth, endOfMonth, subMonths } from 'date-fns';
import {
  Download,
  Calendar,
  TrendingUp,
  RefreshCw,
  BarChart3,
  Sparkles,
  Mail
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import PageHeader from '@/components/ui/PageHeader';
import LoadingSpinner from '@/components/ui/LoadingSpinner';
import SalesInsights from '@/components/dashboard/SalesInsights.js';
import MarketingInsights from '@/components/dashboard/MarketingInsights.js';
import OperationalMetrics from '@/components/dashboard/OperationalMetrics.js';
import MenuProfitability from '@/components/dashboard/MenuProfitability.js';
import FinancialOverview from '@/components/dashboard/FinancialOverview.js';
import TrainingCulture from '@/components/dashboard/TrainingCulture.js';
import PredictiveAnalytics from '@/components/dashboard/PredictiveAnalytics.js';

export default function CommandCenter() {
  const [user, setUser] = useState(null);
  const [dateRange, setDateRange] = useState({
    from: subDays(new Date(), 30),
    to: new Date()
  });
  const [refreshing, setRefreshing] = useState(false);

  useEffect(() => {
    const loadUser = async () => {
      try {
        const userData = await base44.auth.me();
        setUser(userData);
      } catch (e) {}
    };
    loadUser();
  }, []);

  const { data: shifts = [] } = useQuery({
    queryKey: ['shifts-dashboard', format(dateRange.from, 'yyyy-MM-dd')],
    queryFn: () => base44.entities.Shift.filter({
      date: {
        $gte: format(dateRange.from, 'yyyy-MM-dd'),
        $lte: format(dateRange.to, 'yyyy-MM-dd')
      }
    }, '-updated_date', 500)
  });

  const { data: menuItems = [] } = useQuery({
    queryKey: ['menu-items-dashboard'],
    queryFn: () => base44.entities.MenuItem.list()
  });

  const { data: sales = [] } = useQuery({
    queryKey: ['sales-dashboard', format(dateRange.from, 'yyyy-MM-dd')],
    queryFn: () => base44.entities.Sale?.list?.() || [],
  });

  const handleRefresh = async () => {
    setRefreshing(true);
    setTimeout(() => setRefreshing(false), 1000);
  };

  const exportPDF = async () => {
    const html2canvas = (await import('html2canvas')).default;
    const jsPDF = (await import('jspdf')).default;
    
    const element = document.getElementById('dashboard-content');
    const canvas = await html2canvas(element, { scale: 2 });
    const pdf = new jsPDF('l', 'mm', 'a4');
    const imgData = canvas.toDataURL('image/png');
    pdf.addImage(imgData, 'PNG', 10, 10, 277, 190);
    pdf.save(`aura-dashboard-${format(new Date(), 'yyyy-MM-dd')}.pdf`);
  };

  const exportExcel = async () => {
    const XLSX = (await import('xlsx')).default;
    
    const summaryData = [
      ['AURA Performance Command Center', '', ''],
      ['Report Date', format(new Date(), 'yyyy-MM-dd'), ''],
      ['Period', `${format(dateRange.from, 'MMM d')} - ${format(dateRange.to, 'MMM d, yyyy')}`, ''],
      ['', '', ''],
      ['KPI', 'Value', 'Status'],
      ['Total Shifts', shifts.length, 'Active'],
      ['Total Menu Items', menuItems.length, 'Active'],
      ['', '', ''],
      ['Generated by AURA Intelligence System', '', '']
    ];

    const ws = XLSX.utils.aoa_to_sheet(summaryData);
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, 'Dashboard');
    XLSX.writeFile(wb, `aura-dashboard-${format(new Date(), 'yyyy-MM-dd')}.xlsx`);
  };

  const sendReport = async () => {
    if (!user?.email) return;
    try {
      await base44.integrations.Core.SendEmail({
        to: user.email,
        subject: `Weekly AURA Report – ${format(new Date(), 'MMM d, yyyy')}`,
        body: `
Your AURA Performance Command Center Weekly Summary:

Period: ${format(dateRange.from, 'MMM d')} - ${format(dateRange.to, 'MMM d, yyyy')}

📊 Quick Metrics:
• Total Shifts: ${shifts.length}
• Menu Items: ${menuItems.length}
• Data Points: ${shifts.length + menuItems.length}

🔍 Action Items:
Review the Command Center dashboard for detailed insights and AI recommendations.

AI Insights will be available soon with predictive analytics.

---
AURA Intelligence System
`
      });
      alert('✅ Report sent to ' + user.email);
    } catch (error) {
      console.error('Email error:', error);
    }
  };

  const isLoading = !user;

  if (isLoading) return <LoadingSpinner message="Loading Command Center..." />;

  const canViewFinancials = ['owner', 'admin'].includes(user?.role);

  return (
    <div id="dashboard-content" className="space-y-6">
      <PageHeader
        title="AURA Performance Command Center"
        description="Real-time business intelligence with AI-powered predictions"
      />

      {/* Controls */}
      <motion.div
        initial={{ opacity: 0, y: 10 }}
        animate={{ opacity: 1, y: 0 }}
        className="flex flex-wrap gap-3 items-center justify-between bg-gradient-to-r from-emerald-50 to-amber-50 p-4 rounded-xl border border-emerald-200"
      >
        <div className="flex flex-wrap gap-2">
          <Button 
            variant="outline"
            onClick={handleRefresh}
            disabled={refreshing}
            className="gap-2"
          >
            <RefreshCw className={`w-4 h-4 ${refreshing ? 'animate-spin' : ''}`} />
            Refresh
          </Button>
          <Button 
            variant="outline"
            onClick={exportPDF}
            className="gap-2"
          >
            <Download className="w-4 h-4" />
            PDF
          </Button>
          <Button 
            variant="outline"
            onClick={exportExcel}
            className="gap-2"
          >
            <Download className="w-4 h-4" />
            Excel
          </Button>
          <Button 
            variant="outline"
            onClick={sendReport}
            className="gap-2"
          >
            <Mail className="w-4 h-4" />
            Email Report
          </Button>
        </div>
        <Badge className="bg-emerald-600">Live</Badge>
      </motion.div>

      {/* Main Dashboard Tabs */}
      <Tabs defaultValue="sales" className="space-y-6">
        <TabsList className="grid w-full grid-cols-4 lg:grid-cols-7">
          <TabsTrigger value="sales" className="text-xs">
            <TrendingUp className="w-3 h-3 mr-1" />
            Sales
          </TabsTrigger>
          <TabsTrigger value="marketing" className="text-xs">
            📱 Marketing
          </TabsTrigger>
          <TabsTrigger value="operations" className="text-xs">
            ⚙️ Operations
          </TabsTrigger>
          <TabsTrigger value="menu" className="text-xs">
            🥘 Menu
          </TabsTrigger>
          {canViewFinancials && (
            <TabsTrigger value="financial" className="text-xs">
              💰 Financial
            </TabsTrigger>
          )}
          <TabsTrigger value="training" className="text-xs">
            🎓 Training
          </TabsTrigger>
          <TabsTrigger value="forecast" className="text-xs">
            🔮 Forecast
          </TabsTrigger>
        </TabsList>

        {/* Sales Tab */}
        <TabsContent value="sales">
          <SalesInsights shifts={shifts} menuItems={menuItems} dateRange={dateRange} />
        </TabsContent>

        {/* Marketing Tab */}
        <TabsContent value="marketing">
          <MarketingInsights dateRange={dateRange} />
        </TabsContent>

        {/* Operations Tab */}
        <TabsContent value="operations">
          <OperationalMetrics shifts={shifts} dateRange={dateRange} />
        </TabsContent>

        {/* Menu Tab */}
        <TabsContent value="menu">
          <MenuProfitability menuItems={menuItems} shifts={shifts} />
        </TabsContent>

        {/* Financial Tab */}
        {canViewFinancials && (
          <TabsContent value="financial">
            <FinancialOverview shifts={shifts} menuItems={menuItems} dateRange={dateRange} />
          </TabsContent>
        )}

        {/* Training Tab */}
        <TabsContent value="training">
          <TrainingCulture dateRange={dateRange} />
        </TabsContent>

        {/* Forecast Tab */}
        <TabsContent value="forecast">
          <PredictiveAnalytics shifts={shifts} menuItems={menuItems} dateRange={dateRange} />
        </TabsContent>
      </Tabs>
    </div>
  );
}