import React from 'react';
import { Button } from '@/components/ui/button';
import { Download } from 'lucide-react';
import { format } from 'date-fns';

export default function AuditPDFExport({ audit, type = 'weekly' }) {
  const handleExport = () => {
    const printWindow = window.open('', '_blank');
    const content = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>Audit Report - ${audit.audit_week || audit.audit_month}</title>
        <style>
          body { font-family: Arial, sans-serif; padding: 40px; }
          .header { text-align: center; margin-bottom: 30px; }
          .section { margin-bottom: 20px; }
          .score { font-size: 48px; font-weight: bold; color: #10b981; text-align: center; margin: 20px 0; }
          table { width: 100%; border-collapse: collapse; margin: 20px 0; }
          td, th { padding: 10px; border: 1px solid #ddd; text-align: left; }
          th { background-color: #f3f4f6; }
          .footer { margin-top: 40px; font-size: 12px; color: #666; text-align: center; }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>🧾 ${type === 'weekly' ? 'Weekly Review' : 'Monthly Audit'} Report</h1>
          <p>Period: ${audit.audit_week || audit.audit_month}</p>
          <p>Submitted by: ${audit.submitted_by_name}</p>
          <p>Date: ${format(new Date(audit.submission_date || audit.created_date), 'PPP')}</p>
        </div>
        
        <div class="score">${audit.audit_score || audit.overall_score}%</div>
        
        ${type === 'weekly' ? `
          <div class="section">
            <h2>📊 Sales Summary</h2>
            <table>
              <tr><th>Metric</th><th>Value</th></tr>
              <tr><td>Total Sales</td><td>£${audit.sales_summary?.total_sales || 0}</td></tr>
              <tr><td>AOV</td><td>£${audit.sales_summary?.average_order_value || 0}</td></tr>
              <tr><td>Transactions</td><td>${audit.sales_summary?.transactions || 0}</td></tr>
              <tr><td>COGS %</td><td>${audit.sales_summary?.cost_of_goods_percent || 0}%</td></tr>
              <tr><td>Wastage %</td><td>${audit.sales_summary?.wastage_percent || 0}%</td></tr>
            </table>
          </div>
          
          <div class="section">
            <h2>👨‍💼 Staff Performance</h2>
            <table>
              <tr><th>Metric</th><th>Value</th></tr>
              <tr><td>Attendance</td><td>${audit.staff_performance?.attendance_compliance_percent || 0}%</td></tr>
              <tr><td>Training</td><td>${audit.staff_performance?.training_completion_percent || 0}%</td></tr>
              <tr><td>Incidents</td><td>${audit.staff_performance?.incidents_logged || 0}</td></tr>
            </table>
          </div>
          
          <div class="section">
            <h2>✅ Operational Compliance</h2>
            <table>
              <tr><th>Metric</th><th>Value</th></tr>
              <tr><td>Hygiene</td><td>${audit.operational_compliance?.hygiene_checklist_percent || 0}%</td></tr>
              <tr><td>Temperature Logs</td><td>${audit.operational_compliance?.temperature_log_completion_percent || 0}%</td></tr>
            </table>
          </div>
        ` : `
          <div class="section">
            <h2>📋 Audit Summary</h2>
            <p>${audit.ai_summary || 'No summary available'}</p>
          </div>
          
          <div class="section">
            <h2>📊 Compliance Scores</h2>
            <table>
              <tr><th>Category</th><th>Score</th></tr>
              <tr><td>Hygiene</td><td>${audit.compliance_hygiene?.fsa_hygiene_score || 0}%</td></tr>
              <tr><td>Equipment Health</td><td>${audit.compliance_hygiene?.equipment_health_score || 0}%</td></tr>
              <tr><td>Training</td><td>${audit.team_metrics?.training_compliance_percent || 0}%</td></tr>
            </table>
          </div>
        `}
        
        ${audit.comments ? `
          <div class="section">
            <h2>💬 Comments</h2>
            <p>${audit.comments}</p>
          </div>
        ` : ''}
        
        <div class="footer">
          <p>Generated by AURA Restaurant Ops • ${format(new Date(), 'PPP')}</p>
        </div>
      </body>
      </html>
    `;
    
    printWindow.document.write(content);
    printWindow.document.close();
    setTimeout(() => {
      printWindow.print();
    }, 250);
  };

  return (
    <Button onClick={handleExport} variant="outline" size="sm">
      <Download className="w-4 h-4 mr-2" />
      Export PDF
    </Button>
  );
}